#!/usr/bin/env bash
# Rewrite the marker block in README.md so it embeds every PNG in
# docs/screenshots/. The block is delimited by:
#   <!-- BEGIN SCREENSHOTS -->
#   <!-- END SCREENSHOTS -->
# Run from the repository root: packaging/screenshots/embed_in_readme.sh

set -euo pipefail

README="${1:-README.md}"
SHOT_DIR="docs/screenshots"
BEGIN="<!-- BEGIN SCREENSHOTS -->"
END="<!-- END SCREENSHOTS -->"

if ! grep -qF "$BEGIN" "$README" || ! grep -qF "$END" "$README"; then
    echo "error: screenshot markers not found in $README" >&2
    exit 1
fi

# Build the replacement body from the PNGs present (sorted, stable order).
block="$(mktemp)"
{
    shopt -s nullglob
    pngs=("$SHOT_DIR"/*.png)
    if [[ ${#pngs[@]} -eq 0 ]]; then
        echo "_Screenshots are generated by the **Screenshots** GitHub Action._"
    else
        for png in "${pngs[@]}"; do
            # A caption from the file name: main.png -> "Main".
            base="$(basename "$png" .png)"
            caption="$(printf '%s' "$base" | sed 's/[-_]/ /g' \
                | awk '{ for (i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2) }1')"
            printf '![%s](%s)\n\n' "$caption" "$png"
        done
    fi
} > "$block"

# Splice: everything up to and including BEGIN, the new block, then END onward.
out="$(mktemp)"
awk -v begin="$BEGIN" -v end="$END" -v blockfile="$block" '
    $0 ~ begin { print; while ((getline line < blockfile) > 0) print line; skip=1; next }
    $0 ~ end   { skip=0 }
    !skip      { print }
' "$README" > "$out"

mv "$out" "$README"
rm -f "$block"
echo "updated $README with $(ls "$SHOT_DIR"/*.png 2>/dev/null | wc -l | tr -d ' ') screenshot(s)"
